// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"time"
)

type User struct {
	ID int `json:"id"`
	// 用户名
	Nickname string `json:"nickname"`
	// 密码
	Password string `json:"password"`
	// 用户性别
	Gender int `json:"gender"`
	// 年龄
	Age int `json:"age"`
	// 头像
	Avatar string `json:"avatar"`
	// 创建时间
	CreatedAt time.Time `json:"createdAt"`
	// 更新时间
	UpdatedAt time.Time `json:"updatedAt"`
}
